"""Auto generate all

Revision ID: 54b6c75634f1
Revises: 8e5b5aaaf803
Create Date: 2021-11-29 07:10:00.630093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b6c75634f1'
down_revision = '8e5b5aaaf803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
